from django.db import models
from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _


class AdminArea(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    admin_leve = models.CharField(max_length=254, blank=True, null=True)
    right_coun = models.CharField(max_length=254, blank=True, null=True)
    left_count = models.CharField(max_length=254, blank=True, null=True)
    name_fr = models.CharField(max_length=254, blank=True, null=True)
    maritime = models.CharField(max_length=254, blank=True, null=True)
    note_sourc = models.CharField(max_length=254, blank=True, null=True)
    wdb_source = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    boundary = models.CharField(max_length=254, blank=True, null=True)
    border_typ = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiLineStringField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name_en)

    class Meta:
        db_table = 'admin_area'
        verbose_name = _('Admin Area')
        verbose_name_plural = _('Admin Area')


class Boundary(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    boundary = models.CharField(max_length=254, blank=True, null=True)
    wall = models.CharField(max_length=254, blank=True, null=True)
    height = models.CharField(max_length=254, blank=True, null=True)
    barrier = models.CharField(max_length=254, blank=True, null=True)
    right_coun = models.CharField(max_length=254, blank=True, null=True)
    left_count = models.CharField(max_length=254, blank=True, null=True)
    name_fr = models.CharField(max_length=254, blank=True, null=True)
    maritime = models.CharField(max_length=254, blank=True, null=True)
    note_sourc = models.CharField(max_length=254, blank=True, null=True)
    wdb_source = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    border_typ = models.CharField(max_length=254, blank=True, null=True)
    admin_leve = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiLineStringField(srid=4326, blank=True, null=True)


    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'Boundary'
        verbose_name = _('Boundary')
        verbose_name_plural = _('Boundaries')


class Street(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    addr_stree = models.CharField(max_length=254, blank=True, null=True)
    image = models.CharField(max_length=254, blank=True, null=True)
    name_sl = models.CharField(max_length=254, blank=True, null=True)
    name_et = models.CharField(max_length=254, blank=True, null=True)
    name_lt = models.CharField(max_length=254, blank=True, null=True)
    name_lv = models.CharField(max_length=254, blank=True, null=True)
    diet_pesce = models.CharField(max_length=254, blank=True, null=True)
    diet_lacto = models.CharField(max_length=254, blank=True, null=True)
    diet_glute = models.CharField(max_length=254, blank=True, null=True)
    payment_te = models.CharField(max_length=254, blank=True, null=True)
    payment_ma = models.CharField(max_length=254, blank=True, null=True)
    payment_am = models.CharField(max_length=254, blank=True, null=True)
    diet_vegan = models.CharField(max_length=254, blank=True, null=True)
    diet_organ = models.CharField(max_length=254, blank=True, null=True)
    diet_meat = models.CharField(max_length=254, blank=True, null=True)
    diet_koshe = models.CharField(max_length=254, blank=True, null=True)
    diet_halal = models.CharField(max_length=254, blank=True, null=True)
    fee = models.CharField(max_length=254, blank=True, null=True)
    name_ro = models.CharField(max_length=254, blank=True, null=True)
    bar = models.CharField(max_length=254, blank=True, null=True)
    addr_neigh = models.CharField(max_length=254, blank=True, null=True)
    reservatio = models.CharField(max_length=254, blank=True, null=True)
    name_mi = models.CharField(max_length=254, blank=True, null=True)
    alt_name_m = models.CharField(max_length=254, blank=True, null=True)
    alt_name_d = models.CharField(max_length=254, blank=True, null=True)
    addr_full = models.CharField(max_length=254, blank=True, null=True)
    mobile_pho = models.CharField(max_length=254, blank=True, null=True)
    official_n = models.CharField(max_length=254, blank=True, null=True)
    official_1 = models.CharField(max_length=254, blank=True, null=True)
    official_2 = models.CharField(max_length=254, blank=True, null=True)
    official_3 = models.CharField(max_length=254, blank=True, null=True)
    official_4 = models.CharField(max_length=254, blank=True, null=True)
    official_5 = models.CharField(max_length=254, blank=True, null=True)
    official_6 = models.CharField(max_length=254, blank=True, null=True)
    official_7 = models.CharField(max_length=254, blank=True, null=True)
    name_tr = models.CharField(max_length=254, blank=True, null=True)
    name_sq = models.CharField(max_length=254, blank=True, null=True)
    name_pt = models.CharField(max_length=254, blank=True, null=True)
    name_pl = models.CharField(max_length=254, blank=True, null=True)
    name_nl = models.CharField(max_length=254, blank=True, null=True)
    name_lo = models.CharField(max_length=254, blank=True, null=True)
    name_lb = models.CharField(max_length=254, blank=True, null=True)
    name_el = models.CharField(max_length=254, blank=True, null=True)
    name_da = models.CharField(max_length=254, blank=True, null=True)
    name_cs = models.CharField(max_length=254, blank=True, null=True)
    alt_name_n = models.CharField(max_length=254, blank=True, null=True)
    alt_name_f = models.CharField(max_length=254, blank=True, null=True)
    alt_name_e = models.CharField(max_length=254, blank=True, null=True)
    dispensing = models.CharField(max_length=254, blank=True, null=True)
    gate_type = models.CharField(max_length=254, blank=True, null=True)
    toilets_wh = models.CharField(max_length=254, blank=True, null=True)
    name_he = models.CharField(max_length=254, blank=True, null=True)
    addr_unit = models.CharField(max_length=254, blank=True, null=True)
    payment_vi = models.CharField(max_length=254, blank=True, null=True)
    payment_ca = models.CharField(max_length=254, blank=True, null=True)
    internet_a = models.CharField(max_length=254, blank=True, null=True)
    brewery = models.CharField(max_length=254, blank=True, null=True)
    operator_t = models.CharField(max_length=254, blank=True, null=True)
    healthcare = models.CharField(max_length=254, blank=True, null=True)
    facebook = models.CharField(max_length=254, blank=True, null=True)
    clothes = models.CharField(max_length=254, blank=True, null=True)
    antenna = models.CharField(max_length=254, blank=True, null=True)
    brand_wiki = models.CharField(max_length=254, blank=True, null=True)
    service = models.CharField(max_length=254, blank=True, null=True)
    club = models.CharField(max_length=254, blank=True, null=True)
    recycling_field = models.CharField(max_length=254, blank=True, null=True)
    tower_type = models.CharField(max_length=254, blank=True, null=True)
    man_made = models.CharField(max_length=254, blank=True, null=True)
    addr_city_field = models.CharField(max_length=254, blank=True, null=True)
    short_name = models.CharField(max_length=254, blank=True, null=True)
    name_pnb = models.CharField(max_length=254, blank=True, null=True)
    name_ks = models.CharField(max_length=254, blank=True, null=True)
    name_azb = models.CharField(max_length=254, blank=True, null=True)
    brand_pnb = models.CharField(max_length=254, blank=True, null=True)
    brand_ks = models.CharField(max_length=254, blank=True, null=True)
    brand_azb = models.CharField(max_length=254, blank=True, null=True)
    beauty = models.CharField(max_length=254, blank=True, null=True)
    name_zh = models.CharField(max_length=254, blank=True, null=True)
    diplomatic = models.CharField(max_length=254, blank=True, null=True)
    diplomat_1 = models.CharField(max_length=254, blank=True, null=True)
    diplomat_2 = models.CharField(max_length=254, blank=True, null=True)
    contact_yo = models.CharField(max_length=254, blank=True, null=True)
    historic = models.CharField(max_length=254, blank=True, null=True)
    healthca_1 = models.CharField(max_length=254, blank=True, null=True)
    religion = models.CharField(max_length=254, blank=True, null=True)
    name_ko = models.CharField(max_length=254, blank=True, null=True)
    name_hi = models.CharField(max_length=254, blank=True, null=True)
    trade = models.CharField(max_length=254, blank=True, null=True)
    recyclin_1 = models.CharField(max_length=254, blank=True, null=True)
    name_de = models.CharField(max_length=254, blank=True, null=True)
    contact_li = models.CharField(max_length=254, blank=True, null=True)
    descriptio = models.CharField(max_length=254, blank=True, null=True)
    landuse = models.CharField(max_length=254, blank=True, null=True)
    craft = models.CharField(max_length=254, blank=True, null=True)
    payment_no = models.CharField(max_length=254, blank=True, null=True)
    payment_el = models.CharField(max_length=254, blank=True, null=True)
    payment_cr = models.CharField(max_length=254, blank=True, null=True)
    payment_co = models.CharField(max_length=254, blank=True, null=True)
    second_han = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    lit = models.CharField(max_length=254, blank=True, null=True)
    official_8 = models.CharField(max_length=254, blank=True, null=True)
    toilets_di = models.CharField(max_length=254, blank=True, null=True)
    female = models.CharField(max_length=254, blank=True, null=True)
    access = models.CharField(max_length=254, blank=True, null=True)
    drive_thro = models.CharField(max_length=254, blank=True, null=True)
    building_l = models.CharField(max_length=254, blank=True, null=True)
    diet_veget = models.CharField(max_length=254, blank=True, null=True)
    informatio = models.CharField(max_length=254, blank=True, null=True)
    outdoor_se = models.CharField(max_length=254, blank=True, null=True)
    addr_place = models.CharField(max_length=254, blank=True, null=True)
    wheelchair = models.CharField(max_length=254, blank=True, null=True)
    entrance = models.CharField(max_length=254, blank=True, null=True)
    name_ru = models.CharField(max_length=254, blank=True, null=True)
    name_es = models.CharField(max_length=254, blank=True, null=True)
    embassy = models.CharField(max_length=254, blank=True, null=True)
    contact_fa = models.CharField(max_length=254, blank=True, null=True)
    addr_full_field = models.CharField(max_length=254, blank=True, null=True)
    designatio = models.CharField(max_length=254, blank=True, null=True)
    delivery = models.CharField(max_length=254, blank=True, null=True)
    name_sv = models.CharField(max_length=254, blank=True, null=True)
    long_name_field = models.CharField(max_length=254, blank=True, null=True)
    long_name = models.CharField(max_length=254, blank=True, null=True)
    addr_str_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_house = models.CharField(max_length=254, blank=True, null=True)
    addr_hou_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_floor = models.CharField(max_length=254, blank=True, null=True)
    wheelcha_1 = models.CharField(max_length=254, blank=True, null=True)
    tourism = models.CharField(max_length=254, blank=True, null=True)
    stars = models.CharField(max_length=254, blank=True, null=True)
    rooms = models.CharField(max_length=254, blank=True, null=True)
    mapillary = models.CharField(max_length=254, blank=True, null=True)
    internet_1 = models.CharField(max_length=254, blank=True, null=True)
    air_condit = models.CharField(max_length=254, blank=True, null=True)
    internet_2 = models.CharField(max_length=254, blank=True, null=True)
    payment_1 = models.CharField(max_length=254, blank=True, null=True)
    payment_2 = models.CharField(max_length=254, blank=True, null=True)
    payment_de = models.CharField(max_length=254, blank=True, null=True)
    payment_3 = models.CharField(max_length=254, blank=True, null=True)
    payment_4 = models.CharField(max_length=254, blank=True, null=True)
    opening_ho = models.CharField(max_length=254, blank=True, null=True)
    min_age = models.CharField(max_length=254, blank=True, null=True)
    currency_a = models.CharField(max_length=254, blank=True, null=True)
    capacity = models.CharField(max_length=254, blank=True, null=True)
    name_it = models.CharField(max_length=254, blank=True, null=True)
    building = models.CharField(max_length=254, blank=True, null=True)
    wikipedia = models.CharField(max_length=254, blank=True, null=True)
    wikidata = models.CharField(max_length=254, blank=True, null=True)
    level = models.CharField(max_length=254, blank=True, null=True)
    diplomat_3 = models.CharField(max_length=254, blank=True, null=True)
    addr_postc = models.CharField(max_length=254, blank=True, null=True)
    fax = models.CharField(max_length=254, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    addr_distr = models.CharField(max_length=254, blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    smoking = models.CharField(max_length=254, blank=True, null=True)
    atm = models.CharField(max_length=254, blank=True, null=True)
    target = models.CharField(max_length=254, blank=True, null=True)
    office = models.CharField(max_length=254, blank=True, null=True)
    name_fr = models.CharField(max_length=254, blank=True, null=True)
    language_a = models.CharField(max_length=254, blank=True, null=True)
    country = models.CharField(max_length=254, blank=True, null=True)
    alt_name_a = models.CharField(max_length=254, blank=True, null=True)
    alt_name = models.CharField(max_length=254, blank=True, null=True)
    addr_hou_2 = models.CharField(max_length=254, blank=True, null=True)
    phone = models.CharField(max_length=254, blank=True, null=True)
    takeaway = models.CharField(max_length=254, blank=True, null=True)
    name_ur = models.CharField(max_length=254, blank=True, null=True)
    name_pa = models.CharField(max_length=254, blank=True, null=True)
    name_ja = models.CharField(max_length=254, blank=True, null=True)
    name_fa = models.CharField(max_length=254, blank=True, null=True)
    brand_wi_1 = models.CharField(max_length=254, blank=True, null=True)
    brand_wi_2 = models.CharField(max_length=254, blank=True, null=True)
    brand_ur = models.CharField(max_length=254, blank=True, null=True)
    brand_pa = models.CharField(max_length=254, blank=True, null=True)
    brand_fa = models.CharField(max_length=254, blank=True, null=True)
    brand_en = models.CharField(max_length=254, blank=True, null=True)
    brand_ar = models.CharField(max_length=254, blank=True, null=True)
    brand = models.CharField(max_length=254, blank=True, null=True)
    addr_str_2 = models.CharField(max_length=254, blank=True, null=True)
    operator = models.CharField(max_length=254, blank=True, null=True)
    opening_1 = models.CharField(max_length=254, blank=True, null=True)
    contact_we = models.CharField(max_length=254, blank=True, null=True)
    contact_tw = models.CharField(max_length=254, blank=True, null=True)
    contact_ph = models.CharField(max_length=254, blank=True, null=True)
    contact_in = models.CharField(max_length=254, blank=True, null=True)
    contact_1 = models.CharField(max_length=254, blank=True, null=True)
    contact_em = models.CharField(max_length=254, blank=True, null=True)
    addr_cit_1 = models.CharField(max_length=254, blank=True, null=True)
    shop = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    cuisine = models.CharField(max_length=254, blank=True, null=True)
    amenity = models.CharField(max_length=254, blank=True, null=True)
    addr_hou_3 = models.CharField(max_length=254, blank=True, null=True)
    addr_count = models.CharField(max_length=254, blank=True, null=True)
    addr_city = models.CharField(max_length=254, blank=True, null=True)
    sport = models.CharField(max_length=254, blank=True, null=True)
    leisure = models.CharField(max_length=254, blank=True, null=True)
    covered = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPointField(srid=4326, blank=True, null=True)


    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'street'
        verbose_name = _('Street')
        verbose_name_plural = _('Street')


class Amenity(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    amenity = models.CharField(max_length=254, blank=True, null=True)
    diet_pesce = models.CharField(max_length=254, blank=True, null=True)
    diet_lacto = models.CharField(max_length=254, blank=True, null=True)
    diet_glute = models.CharField(max_length=254, blank=True, null=True)
    diet_organ = models.CharField(max_length=254, blank=True, null=True)
    diet_meat = models.CharField(max_length=254, blank=True, null=True)
    backrest = models.CharField(max_length=254, blank=True, null=True)
    diet_koshe = models.CharField(max_length=254, blank=True, null=True)
    diet_halal = models.CharField(max_length=254, blank=True, null=True)
    seats = models.CharField(max_length=254, blank=True, null=True)
    material = models.CharField(max_length=254, blank=True, null=True)
    colour = models.CharField(max_length=254, blank=True, null=True)
    bar = models.CharField(max_length=254, blank=True, null=True)
    addr_neigh = models.CharField(max_length=254, blank=True, null=True)
    fuel_lpg = models.CharField(max_length=254, blank=True, null=True)
    fuel_octan = models.CharField(max_length=254, blank=True, null=True)
    fuel_oct_1 = models.CharField(max_length=254, blank=True, null=True)
    fuel_oct_2 = models.CharField(max_length=254, blank=True, null=True)
    noexit = models.CharField(max_length=254, blank=True, null=True)
    stars = models.CharField(max_length=254, blank=True, null=True)
    reservatio = models.CharField(max_length=254, blank=True, null=True)
    lit = models.CharField(max_length=254, blank=True, null=True)
    bin = models.CharField(max_length=254, blank=True, null=True)
    mobile_pho = models.CharField(max_length=254, blank=True, null=True)
    url = models.CharField(max_length=254, blank=True, null=True)
    name_uk = models.CharField(max_length=254, blank=True, null=True)
    bench = models.CharField(max_length=254, blank=True, null=True)
    shelter_ty = models.CharField(max_length=254, blank=True, null=True)
    contact_yo = models.CharField(max_length=254, blank=True, null=True)
    toilets_ac = models.CharField(max_length=254, blank=True, null=True)
    toilets = models.CharField(max_length=254, blank=True, null=True)
    vending = models.CharField(max_length=254, blank=True, null=True)
    addr_unit = models.CharField(max_length=254, blank=True, null=True)
    crossing = models.CharField(max_length=254, blank=True, null=True)
    payment_vi = models.CharField(max_length=254, blank=True, null=True)
    payment_no = models.CharField(max_length=254, blank=True, null=True)
    payment_de = models.CharField(max_length=254, blank=True, null=True)
    payment_co = models.CharField(max_length=254, blank=True, null=True)
    payment_ca = models.CharField(max_length=254, blank=True, null=True)
    min_age = models.CharField(max_length=254, blank=True, null=True)
    internet_a = models.CharField(max_length=254, blank=True, null=True)
    brewery = models.CharField(max_length=254, blank=True, null=True)
    operator_t = models.CharField(max_length=254, blank=True, null=True)
    healthcare = models.CharField(max_length=254, blank=True, null=True)
    payment_1 = models.CharField(max_length=254, blank=True, null=True)
    payment_ma = models.CharField(max_length=254, blank=True, null=True)
    payment_cr = models.CharField(max_length=254, blank=True, null=True)
    addr_stree = models.CharField(max_length=254, blank=True, null=True)
    office = models.CharField(max_length=254, blank=True, null=True)
    public_tra = models.CharField(max_length=254, blank=True, null=True)
    bus = models.CharField(max_length=254, blank=True, null=True)
    facebook = models.CharField(max_length=254, blank=True, null=True)
    short_name = models.CharField(max_length=254, blank=True, null=True)
    name_zh = models.CharField(max_length=254, blank=True, null=True)
    name_pnb = models.CharField(max_length=254, blank=True, null=True)
    name_ks = models.CharField(max_length=254, blank=True, null=True)
    name_azb = models.CharField(max_length=254, blank=True, null=True)
    brand_pnb = models.CharField(max_length=254, blank=True, null=True)
    brand_ks = models.CharField(max_length=254, blank=True, null=True)
    brand_azb = models.CharField(max_length=254, blank=True, null=True)
    motorcycle = models.CharField(max_length=254, blank=True, null=True)
    motorcar = models.CharField(max_length=254, blank=True, null=True)
    foot = models.CharField(max_length=254, blank=True, null=True)
    bicycle = models.CharField(max_length=254, blank=True, null=True)
    toilets_wh = models.CharField(max_length=254, blank=True, null=True)
    diet_vegan = models.CharField(max_length=254, blank=True, null=True)
    name_ru = models.CharField(max_length=254, blank=True, null=True)
    name_ko = models.CharField(max_length=254, blank=True, null=True)
    phone_1 = models.CharField(max_length=254, blank=True, null=True)
    phone_mobi = models.CharField(max_length=254, blank=True, null=True)
    addr_ref = models.CharField(max_length=254, blank=True, null=True)
    contact_li = models.CharField(max_length=254, blank=True, null=True)
    currency_a = models.CharField(max_length=254, blank=True, null=True)
    craft = models.CharField(max_length=254, blank=True, null=True)
    services = models.CharField(max_length=254, blank=True, null=True)
    air_condit = models.CharField(max_length=254, blank=True, null=True)
    opening_ho = models.CharField(max_length=254, blank=True, null=True)
    wikidata = models.CharField(max_length=254, blank=True, null=True)
    public_boo = models.CharField(max_length=254, blank=True, null=True)
    location = models.CharField(max_length=254, blank=True, null=True)
    name_ro = models.CharField(max_length=254, blank=True, null=True)
    denominati = models.CharField(max_length=254, blank=True, null=True)
    payment_el = models.CharField(max_length=254, blank=True, null=True)
    payment_2 = models.CharField(max_length=254, blank=True, null=True)
    payment_3 = models.CharField(max_length=254, blank=True, null=True)
    indoor = models.CharField(max_length=254, blank=True, null=True)
    drinking_w = models.CharField(max_length=254, blank=True, null=True)
    descriptio = models.CharField(max_length=254, blank=True, null=True)
    image = models.CharField(max_length=254, blank=True, null=True)
    unisex = models.CharField(max_length=254, blank=True, null=True)
    male = models.CharField(max_length=254, blank=True, null=True)
    place_of_w = models.CharField(max_length=254, blank=True, null=True)
    recycling_field = models.CharField(max_length=254, blank=True, null=True)
    recyclin_1 = models.CharField(max_length=254, blank=True, null=True)
    female = models.CharField(max_length=254, blank=True, null=True)
    alt_name = models.CharField(max_length=254, blank=True, null=True)
    addr_place = models.CharField(max_length=254, blank=True, null=True)
    toilets_po = models.CharField(max_length=254, blank=True, null=True)
    toilets_di = models.CharField(max_length=254, blank=True, null=True)
    addr_subur = models.CharField(max_length=254, blank=True, null=True)
    addr_sub_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_state = models.CharField(max_length=254, blank=True, null=True)
    addr_sta_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_provi = models.CharField(max_length=254, blank=True, null=True)
    addr_pro_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_pla_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_pla_2 = models.CharField(max_length=254, blank=True, null=True)
    addr_city_field = models.CharField(max_length=254, blank=True, null=True)
    wheelchair = models.CharField(max_length=254, blank=True, null=True)
    diet_veget = models.CharField(max_length=254, blank=True, null=True)
    layer = models.CharField(max_length=254, blank=True, null=True)
    self_servi = models.CharField(max_length=254, blank=True, null=True)
    name_de = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    supervised = models.CharField(max_length=254, blank=True, null=True)
    dispensing = models.CharField(max_length=254, blank=True, null=True)
    delivery = models.CharField(max_length=254, blank=True, null=True)
    level = models.CharField(max_length=254, blank=True, null=True)
    natural = models.CharField(max_length=254, blank=True, null=True)
    designatio = models.CharField(max_length=254, blank=True, null=True)
    internet_1 = models.CharField(max_length=254, blank=True, null=True)
    outdoor_se = models.CharField(max_length=254, blank=True, null=True)
    highway = models.CharField(max_length=254, blank=True, null=True)
    addr_postc = models.CharField(max_length=254, blank=True, null=True)
    fuel_diese = models.CharField(max_length=254, blank=True, null=True)
    fee = models.CharField(max_length=254, blank=True, null=True)
    wifi = models.CharField(max_length=254, blank=True, null=True)
    capacity = models.CharField(max_length=254, blank=True, null=True)
    addr_house = models.CharField(max_length=254, blank=True, null=True)
    entrance = models.CharField(max_length=254, blank=True, null=True)
    fax = models.CharField(max_length=254, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    addr_distr = models.CharField(max_length=254, blank=True, null=True)
    wheelcha_1 = models.CharField(max_length=254, blank=True, null=True)
    ref = models.CharField(max_length=254, blank=True, null=True)
    smoking = models.CharField(max_length=254, blank=True, null=True)
    parking = models.CharField(max_length=254, blank=True, null=True)
    building = models.CharField(max_length=254, blank=True, null=True)
    is_in = models.CharField(max_length=254, blank=True, null=True)
    drive_thro = models.CharField(max_length=254, blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    phone = models.CharField(max_length=254, blank=True, null=True)
    internet_2 = models.CharField(max_length=254, blank=True, null=True)
    takeaway = models.CharField(max_length=254, blank=True, null=True)
    name_ur = models.CharField(max_length=254, blank=True, null=True)
    name_pa = models.CharField(max_length=254, blank=True, null=True)
    name_ja = models.CharField(max_length=254, blank=True, null=True)
    name_fa = models.CharField(max_length=254, blank=True, null=True)
    brand_ur = models.CharField(max_length=254, blank=True, null=True)
    brand_pa = models.CharField(max_length=254, blank=True, null=True)
    brand_fa = models.CharField(max_length=254, blank=True, null=True)
    addr_str_1 = models.CharField(max_length=254, blank=True, null=True)
    contact_we = models.CharField(max_length=254, blank=True, null=True)
    contact_tw = models.CharField(max_length=254, blank=True, null=True)
    contact_ph = models.CharField(max_length=254, blank=True, null=True)
    contact_in = models.CharField(max_length=254, blank=True, null=True)
    contact_fa = models.CharField(max_length=254, blank=True, null=True)
    contact_em = models.CharField(max_length=254, blank=True, null=True)
    addr_cit_1 = models.CharField(max_length=254, blank=True, null=True)
    healthca_1 = models.CharField(max_length=254, blank=True, null=True)
    emergency = models.CharField(max_length=254, blank=True, null=True)
    opening_1 = models.CharField(max_length=254, blank=True, null=True)
    dress_code = models.CharField(max_length=254, blank=True, null=True)
    religion = models.CharField(max_length=254, blank=True, null=True)
    atm = models.CharField(max_length=254, blank=True, null=True)
    official_n = models.CharField(max_length=254, blank=True, null=True)
    shop = models.CharField(max_length=254, blank=True, null=True)
    operator = models.CharField(max_length=254, blank=True, null=True)
    brand_wiki = models.CharField(max_length=254, blank=True, null=True)
    brand_wi_1 = models.CharField(max_length=254, blank=True, null=True)
    brand_en = models.CharField(max_length=254, blank=True, null=True)
    brand_ar = models.CharField(max_length=254, blank=True, null=True)
    brand = models.CharField(max_length=254, blank=True, null=True)
    access = models.CharField(max_length=254, blank=True, null=True)
    addr_str_2 = models.CharField(max_length=254, blank=True, null=True)
    addr_hou_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_count = models.CharField(max_length=254, blank=True, null=True)
    addr_city = models.CharField(max_length=254, blank=True, null=True)
    service = models.CharField(max_length=254, blank=True, null=True)
    barrier = models.CharField(max_length=254, blank=True, null=True)
    cuisine = models.CharField(max_length=254, blank=True, null=True)
    ele = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPointField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'amenity'
        verbose_name = _('Amenity')
        verbose_name_plural = _('Amenity')


class Bicycle(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    bicycle = models.CharField(max_length=254, blank=True, null=True)
    crossing_i = models.CharField(max_length=254, blank=True, null=True)
    cycleway = models.CharField(max_length=254, blank=True, null=True)
    barrier = models.CharField(max_length=254, blank=True, null=True)
    handrail = models.CharField(max_length=254, blank=True, null=True)
    footway = models.CharField(max_length=254, blank=True, null=True)
    segregated = models.CharField(max_length=254, blank=True, null=True)
    wheelchair = models.CharField(max_length=254, blank=True, null=True)
    incline = models.CharField(max_length=254, blank=True, null=True)
    service = models.CharField(max_length=254, blank=True, null=True)
    motor_vehi = models.CharField(max_length=254, blank=True, null=True)
    bridge = models.CharField(max_length=254, blank=True, null=True)
    level = models.CharField(max_length=254, blank=True, null=True)
    cutting = models.CharField(max_length=254, blank=True, null=True)
    constructi = models.CharField(max_length=254, blank=True, null=True)
    tunnel = models.CharField(max_length=254, blank=True, null=True)
    maxheight = models.CharField(max_length=254, blank=True, null=True)
    layer = models.CharField(max_length=254, blank=True, null=True)
    horse = models.CharField(max_length=254, blank=True, null=True)
    ref_ar = models.CharField(max_length=254, blank=True, null=True)
    foot = models.CharField(max_length=254, blank=True, null=True)
    alt_name = models.CharField(max_length=254, blank=True, null=True)
    access = models.CharField(max_length=254, blank=True, null=True)
    width = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    ref = models.CharField(max_length=254, blank=True, null=True)
    oneway = models.CharField(max_length=254, blank=True, null=True)
    old_name_1 = models.CharField(max_length=254, blank=True, null=True)
    old_name = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    maxspeed = models.CharField(max_length=254, blank=True, null=True)
    lit = models.CharField(max_length=254, blank=True, null=True)
    lanes = models.CharField(max_length=254, blank=True, null=True)
    highway = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiLineStringField(srid=4326, blank=True, null=True)


    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'bicycle'
        verbose_name = _('Bicycle')
        verbose_name_plural = _('Bicycle')


class Bridge(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    bridge = models.CharField(max_length=254, blank=True, null=True)
    usage = models.CharField(max_length=254, blank=True, null=True)
    segregated = models.CharField(max_length=254, blank=True, null=True)
    railway = models.CharField(max_length=254, blank=True, null=True)
    crossing_i = models.CharField(max_length=254, blank=True, null=True)
    man_made = models.CharField(max_length=254, blank=True, null=True)
    width = models.CharField(max_length=254, blank=True, null=True)
    wikipedia = models.CharField(max_length=254, blank=True, null=True)
    wikidata = models.CharField(max_length=254, blank=True, null=True)
    start_date = models.CharField(max_length=254, blank=True, null=True)
    roller_coa = models.CharField(max_length=254, blank=True, null=True)
    operator = models.CharField(max_length=254, blank=True, null=True)
    manufactur = models.CharField(max_length=254, blank=True, null=True)
    attraction = models.CharField(max_length=254, blank=True, null=True)
    turn_lanes = models.CharField(max_length=254, blank=True, null=True)
    covered = models.CharField(max_length=254, blank=True, null=True)
    crossing = models.CharField(max_length=254, blank=True, null=True)
    opening_da = models.CharField(max_length=254, blank=True, null=True)
    indoor = models.CharField(max_length=254, blank=True, null=True)
    barrier = models.CharField(max_length=254, blank=True, null=True)
    height = models.CharField(max_length=254, blank=True, null=True)
    footway = models.CharField(max_length=254, blank=True, null=True)
    tracktype = models.CharField(max_length=254, blank=True, null=True)
    abandoned_field = models.CharField(max_length=254, blank=True, null=True)
    maxspeed_t = models.CharField(max_length=254, blank=True, null=True)
    maxspeed_f = models.CharField(max_length=254, blank=True, null=True)
    incline = models.CharField(max_length=254, blank=True, null=True)
    horse = models.CharField(max_length=254, blank=True, null=True)
    bicycle = models.CharField(max_length=254, blank=True, null=True)
    junction_r = models.CharField(max_length=254, blank=True, null=True)
    service = models.CharField(max_length=254, blank=True, null=True)
    causeway = models.CharField(max_length=254, blank=True, null=True)
    noname = models.CharField(max_length=254, blank=True, null=True)
    motor_vehi = models.CharField(max_length=254, blank=True, null=True)
    check_date = models.CharField(max_length=254, blank=True, null=True)
    level = models.CharField(max_length=254, blank=True, null=True)
    architect_field = models.CharField(max_length=254, blank=True, null=True)
    architec_1 = models.CharField(max_length=254, blank=True, null=True)
    architect = models.CharField(max_length=254, blank=True, null=True)
    constructi = models.CharField(max_length=254, blank=True, null=True)
    maxheight = models.CharField(max_length=254, blank=True, null=True)
    ref_ar = models.CharField(max_length=254, blank=True, null=True)
    maxspeed_h = models.CharField(max_length=254, blank=True, null=True)
    loc_name = models.CharField(max_length=254, blank=True, null=True)
    alt_name = models.CharField(max_length=254, blank=True, null=True)
    access = models.CharField(max_length=254, blank=True, null=True)
    junction = models.CharField(max_length=254, blank=True, null=True)
    old_name_2 = models.CharField(max_length=254, blank=True, null=True)
    old_name_1 = models.CharField(max_length=254, blank=True, null=True)
    old_name_3 = models.CharField(max_length=254, blank=True, null=True)
    lit = models.CharField(max_length=254, blank=True, null=True)
    old_name = models.CharField(max_length=254, blank=True, null=True)
    foot = models.CharField(max_length=254, blank=True, null=True)
    destinatio = models.CharField(max_length=254, blank=True, null=True)
    destinat_1 = models.CharField(max_length=254, blank=True, null=True)
    destinat_2 = models.CharField(max_length=254, blank=True, null=True)
    destinat_3 = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    ref = models.CharField(max_length=254, blank=True, null=True)
    oneway = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    maxspeed = models.CharField(max_length=254, blank=True, null=True)
    layer = models.CharField(max_length=254, blank=True, null=True)
    lanes = models.CharField(max_length=254, blank=True, null=True)
    highway = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiLineStringField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'bridge'
        verbose_name = _('Bridge')
        verbose_name_plural = _('Bridge')

    

class Building(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    building = models.CharField(max_length=254, blank=True, null=True)
    vending = models.CharField(max_length=254, blank=True, null=True)
    natural = models.CharField(max_length=254, blank=True, null=True)
    tourism = models.CharField(max_length=254, blank=True, null=True)
    government = models.CharField(max_length=254, blank=True, null=True)
    foot = models.CharField(max_length=254, blank=True, null=True)
    descriptio = models.CharField(max_length=254, blank=True, null=True)
    addr_stree = models.CharField(max_length=254, blank=True, null=True)
    addr_city_field = models.CharField(max_length=254, blank=True, null=True)
    denominati = models.CharField(max_length=254, blank=True, null=True)
    religion = models.CharField(max_length=254, blank=True, null=True)
    internet_a = models.CharField(max_length=254, blank=True, null=True)
    emergency = models.CharField(max_length=254, blank=True, null=True)
    railway = models.CharField(max_length=254, blank=True, null=True)
    wikipedia = models.CharField(max_length=254, blank=True, null=True)
    wikidata = models.CharField(max_length=254, blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    phone = models.CharField(max_length=254, blank=True, null=True)
    building_l = models.CharField(max_length=254, blank=True, null=True)
    addr_postc = models.CharField(max_length=254, blank=True, null=True)
    office = models.CharField(max_length=254, blank=True, null=True)
    highway = models.CharField(max_length=254, blank=True, null=True)
    level = models.CharField(max_length=254, blank=True, null=True)
    layer = models.CharField(max_length=254, blank=True, null=True)
    name_ur = models.CharField(max_length=254, blank=True, null=True)
    name_pnb = models.CharField(max_length=254, blank=True, null=True)
    name_kk_ar = models.CharField(max_length=254, blank=True, null=True)
    name_fa = models.CharField(max_length=254, blank=True, null=True)
    name_de = models.CharField(max_length=254, blank=True, null=True)
    name_ru = models.CharField(max_length=254, blank=True, null=True)
    wheelchair = models.CharField(max_length=254, blank=True, null=True)
    supervised = models.CharField(max_length=254, blank=True, null=True)
    parking = models.CharField(max_length=254, blank=True, null=True)
    fee = models.CharField(max_length=254, blank=True, null=True)
    access = models.CharField(max_length=254, blank=True, null=True)
    addr_house = models.CharField(max_length=254, blank=True, null=True)
    operator = models.CharField(max_length=254, blank=True, null=True)
    aeroway = models.CharField(max_length=254, blank=True, null=True)
    addr_str_1 = models.CharField(max_length=254, blank=True, null=True)
    opening_ho = models.CharField(max_length=254, blank=True, null=True)
    healthcare = models.CharField(max_length=254, blank=True, null=True)
    amenity = models.CharField(max_length=254, blank=True, null=True)
    entrance = models.CharField(max_length=254, blank=True, null=True)
    shop = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    addr_hou_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_count = models.CharField(max_length=254, blank=True, null=True)
    addr_city = models.CharField(max_length=254, blank=True, null=True)
    barrier = models.CharField(max_length=254, blank=True, null=True)
    sport = models.CharField(max_length=254, blank=True, null=True)
    leisure = models.CharField(max_length=254, blank=True, null=True)
    covered = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPointField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'building'
        verbose_name = _('Building')
        verbose_name_plural = _('Buildings')


class Cycleway(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    cycleway = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    crossing_i = models.CharField(max_length=254, blank=True, null=True)
    bicycle = models.CharField(max_length=254, blank=True, null=True)
    highway = models.CharField(max_length=254, blank=True, null=True)
    foot = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiLineStringField(srid=4326, blank=True, null=True)


    def __str__(self):
        return str(self.cycleway)

    class Meta:
        db_table = 'cycleway'
        verbose_name = _('Cycleway')
        verbose_name_plural = _('Cycleway')


class Embassy(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    embassy = models.CharField(max_length=254, blank=True, null=True)
    name_sl = models.CharField(max_length=254, blank=True, null=True)
    name_et = models.CharField(max_length=254, blank=True, null=True)
    name_lt = models.CharField(max_length=254, blank=True, null=True)
    name_lv = models.CharField(max_length=254, blank=True, null=True)
    name_ro = models.CharField(max_length=254, blank=True, null=True)
    descriptio = models.CharField(max_length=254, blank=True, null=True)
    contact_fa = models.CharField(max_length=254, blank=True, null=True)
    name_mi = models.CharField(max_length=254, blank=True, null=True)
    alt_name_m = models.CharField(max_length=254, blank=True, null=True)
    official_n = models.CharField(max_length=254, blank=True, null=True)
    official_1 = models.CharField(max_length=254, blank=True, null=True)
    official_2 = models.CharField(max_length=254, blank=True, null=True)
    official_3 = models.CharField(max_length=254, blank=True, null=True)
    official_4 = models.CharField(max_length=254, blank=True, null=True)
    official_5 = models.CharField(max_length=254, blank=True, null=True)
    official_6 = models.CharField(max_length=254, blank=True, null=True)
    official_7 = models.CharField(max_length=254, blank=True, null=True)
    name_tr = models.CharField(max_length=254, blank=True, null=True)
    name_sq = models.CharField(max_length=254, blank=True, null=True)
    name_pt = models.CharField(max_length=254, blank=True, null=True)
    name_pl = models.CharField(max_length=254, blank=True, null=True)
    name_nl = models.CharField(max_length=254, blank=True, null=True)
    name_lo = models.CharField(max_length=254, blank=True, null=True)
    name_lb = models.CharField(max_length=254, blank=True, null=True)
    name_ja = models.CharField(max_length=254, blank=True, null=True)
    name_it = models.CharField(max_length=254, blank=True, null=True)
    name_el = models.CharField(max_length=254, blank=True, null=True)
    name_da = models.CharField(max_length=254, blank=True, null=True)
    name_cs = models.CharField(max_length=254, blank=True, null=True)
    alt_name_n = models.CharField(max_length=254, blank=True, null=True)
    alt_name_f = models.CharField(max_length=254, blank=True, null=True)
    addr_unit = models.CharField(max_length=254, blank=True, null=True)
    addr_count = models.CharField(max_length=254, blank=True, null=True)
    name_uk = models.CharField(max_length=254, blank=True, null=True)
    alt_name_u = models.CharField(max_length=254, blank=True, null=True)
    alt_name = models.CharField(max_length=254, blank=True, null=True)
    name_zh = models.CharField(max_length=254, blank=True, null=True)
    diplomatic = models.CharField(max_length=254, blank=True, null=True)
    diplomat_1 = models.CharField(max_length=254, blank=True, null=True)
    diplomat_2 = models.CharField(max_length=254, blank=True, null=True)
    addr_postc = models.CharField(max_length=254, blank=True, null=True)
    name_hi = models.CharField(max_length=254, blank=True, null=True)
    addr_full = models.CharField(max_length=254, blank=True, null=True)
    name_ru = models.CharField(max_length=254, blank=True, null=True)
    addr_distr = models.CharField(max_length=254, blank=True, null=True)
    fax = models.CharField(max_length=254, blank=True, null=True)
    opening_ho = models.CharField(max_length=254, blank=True, null=True)
    name_ur = models.CharField(max_length=254, blank=True, null=True)
    addr_postb = models.CharField(max_length=254, blank=True, null=True)
    addr_house = models.CharField(max_length=254, blank=True, null=True)
    addr_city_field = models.CharField(max_length=254, blank=True, null=True)
    name_fr = models.CharField(max_length=254, blank=True, null=True)
    name_es = models.CharField(max_length=254, blank=True, null=True)
    contact_we = models.CharField(max_length=254, blank=True, null=True)
    contact_ph = models.CharField(max_length=254, blank=True, null=True)
    contact_1 = models.CharField(max_length=254, blank=True, null=True)
    contact_em = models.CharField(max_length=254, blank=True, null=True)
    addr_stree = models.CharField(max_length=254, blank=True, null=True)
    addr_full_field = models.CharField(max_length=254, blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    name_de = models.CharField(max_length=254, blank=True, null=True)
    level = models.CharField(max_length=254, blank=True, null=True)
    alt_name_e = models.CharField(max_length=254, blank=True, null=True)
    alt_name_d = models.CharField(max_length=254, blank=True, null=True)
    wikipedia = models.CharField(max_length=254, blank=True, null=True)
    wikidata = models.CharField(max_length=254, blank=True, null=True)
    phone = models.CharField(max_length=254, blank=True, null=True)
    official_8 = models.CharField(max_length=254, blank=True, null=True)
    official_9 = models.CharField(max_length=254, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    addr_city = models.CharField(max_length=254, blank=True, null=True)
    target = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    office = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    diplomat_3 = models.CharField(max_length=254, blank=True, null=True)
    country = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPointField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'embassy'
        verbose_name = _('Embassy')
        verbose_name_plural = _('Embassy')


class Emergency(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    emergency = models.CharField(max_length=254, blank=True, null=True)
    addr_city = models.CharField(max_length=254, blank=True, null=True)
    type = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    healthcare = models.CharField(max_length=254, blank=True, null=True)
    building_l = models.CharField(max_length=254, blank=True, null=True)
    building = models.CharField(max_length=254, blank=True, null=True)
    amenity = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'emergency'
        verbose_name = _('Emergency')
        verbose_name_plural = _('Emergency')


class Golf(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    golf = models.CharField(max_length=254, blank=True, null=True)
    ref = models.CharField(max_length=254, blank=True, null=True)
    leisure = models.CharField(max_length=254, blank=True, null=True)
    landuse = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    sport = models.CharField(max_length=254, blank=True, null=True)
    type = models.CharField(max_length=254, blank=True, null=True)
    natural = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'golf'
        verbose_name = _('Golf')
        verbose_name_plural = _('Golf')


class Government(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    government = models.CharField(max_length=254, blank=True, null=True)
    wikipedia_field = models.CharField(max_length=254, blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    alt_name = models.CharField(max_length=254, blank=True, null=True)
    operator = models.CharField(max_length=254, blank=True, null=True)
    height = models.CharField(max_length=254, blank=True, null=True)
    building_m = models.CharField(max_length=254, blank=True, null=True)
    addr_city_field = models.CharField(max_length=254, blank=True, null=True)
    addr_city = models.CharField(max_length=254, blank=True, null=True)
    building_l = models.CharField(max_length=254, blank=True, null=True)
    office = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    building = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'government'
        verbose_name = _('Government')
        verbose_name_plural = _('Government')


class Highway(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    highway = models.CharField(max_length=254, blank=True, null=True)
    name_hi = models.CharField(max_length=254, blank=True, null=True)
    name_he = models.CharField(max_length=254, blank=True, null=True)
    bus = models.CharField(max_length=254, blank=True, null=True)
    destinatio = models.CharField(max_length=254, blank=True, null=True)
    leisure = models.CharField(max_length=254, blank=True, null=True)
    building_l = models.CharField(max_length=254, blank=True, null=True)
    node = models.CharField(max_length=254, blank=True, null=True)
    cycleway = models.CharField(max_length=254, blank=True, null=True)
    cycleway_r = models.CharField(max_length=254, blank=True, null=True)
    crossing_i = models.CharField(max_length=254, blank=True, null=True)
    access_con = models.CharField(max_length=254, blank=True, null=True)
    traffic_ca = models.CharField(max_length=254, blank=True, null=True)
    man_made = models.CharField(max_length=254, blank=True, null=True)
    name_en1 = models.CharField(max_length=254, blank=True, null=True)
    non = models.CharField(max_length=254, blank=True, null=True)
    motorroad = models.CharField(max_length=254, blank=True, null=True)
    hide = models.CharField(max_length=254, blank=True, null=True)
    conveying = models.CharField(max_length=254, blank=True, null=True)
    indoor = models.CharField(max_length=254, blank=True, null=True)
    barrier = models.CharField(max_length=254, blank=True, null=True)
    handrail = models.CharField(max_length=254, blank=True, null=True)
    smoothness = models.CharField(max_length=254, blank=True, null=True)
    vehicle = models.CharField(max_length=254, blank=True, null=True)
    height = models.CharField(max_length=254, blank=True, null=True)
    abandoned = models.CharField(max_length=254, blank=True, null=True)
    wheelchair = models.CharField(max_length=254, blank=True, null=True)
    waterway = models.CharField(max_length=254, blank=True, null=True)
    crossing = models.CharField(max_length=254, blank=True, null=True)
    tree_lined = models.CharField(max_length=254, blank=True, null=True)
    tracktype = models.CharField(max_length=254, blank=True, null=True)
    lanes_forw = models.CharField(max_length=254, blank=True, null=True)
    lanes_back = models.CharField(max_length=254, blank=True, null=True)
    embankment = models.CharField(max_length=254, blank=True, null=True)
    abandoned_field = models.CharField(max_length=254, blank=True, null=True)
    maxspeed_f = models.CharField(max_length=254, blank=True, null=True)
    power = models.CharField(max_length=254, blank=True, null=True)
    roundabout = models.CharField(max_length=254, blank=True, null=True)
    disused = models.CharField(max_length=254, blank=True, null=True)
    destinat_1 = models.CharField(max_length=254, blank=True, null=True)
    destinat_2 = models.CharField(max_length=254, blank=True, null=True)
    footway = models.CharField(max_length=254, blank=True, null=True)
    segregated = models.CharField(max_length=254, blank=True, null=True)
    golf_cart = models.CharField(max_length=254, blank=True, null=True)
    sport = models.CharField(max_length=254, blank=True, null=True)
    causeway = models.CharField(max_length=254, blank=True, null=True)
    alt_name_a = models.CharField(max_length=254, blank=True, null=True)
    maxspeed_t = models.CharField(max_length=254, blank=True, null=True)
    check_date = models.CharField(max_length=254, blank=True, null=True)
    trail_visi = models.CharField(max_length=254, blank=True, null=True)
    turn_lanes = models.CharField(max_length=254, blank=True, null=True)
    destinat_3 = models.CharField(max_length=254, blank=True, null=True)
    descriptio = models.CharField(max_length=254, blank=True, null=True)
    level = models.CharField(max_length=254, blank=True, null=True)
    architect_field = models.CharField(max_length=254, blank=True, null=True)
    architec_1 = models.CharField(max_length=254, blank=True, null=True)
    architect = models.CharField(max_length=254, blank=True, null=True)
    covered = models.CharField(max_length=254, blank=True, null=True)
    horse = models.CharField(max_length=254, blank=True, null=True)
    incline = models.CharField(max_length=254, blank=True, null=True)
    cutting = models.CharField(max_length=254, blank=True, null=True)
    ref_ar = models.CharField(max_length=254, blank=True, null=True)
    operator = models.CharField(max_length=254, blank=True, null=True)
    width = models.CharField(max_length=254, blank=True, null=True)
    bicycle = models.CharField(max_length=254, blank=True, null=True)
    opening_da = models.CharField(max_length=254, blank=True, null=True)
    constructi = models.CharField(max_length=254, blank=True, null=True)
    old_name_a = models.CharField(max_length=254, blank=True, null=True)
    noname = models.CharField(max_length=254, blank=True, null=True)
    maxspeed_a = models.CharField(max_length=254, blank=True, null=True)
    old_name_2 = models.CharField(max_length=254, blank=True, null=True)
    is_in = models.CharField(max_length=254, blank=True, null=True)
    old_name_1 = models.CharField(max_length=254, blank=True, null=True)
    old_name_e = models.CharField(max_length=254, blank=True, null=True)
    maxspeed_h = models.CharField(max_length=254, blank=True, null=True)
    tunnel = models.CharField(max_length=254, blank=True, null=True)
    sidewalk = models.CharField(max_length=254, blank=True, null=True)
    name_de = models.CharField(max_length=254, blank=True, null=True)
    alt_name_e = models.CharField(max_length=254, blank=True, null=True)
    old_name_3 = models.CharField(max_length=254, blank=True, null=True)
    hgv = models.CharField(max_length=254, blank=True, null=True)
    motor_vehi = models.CharField(max_length=254, blank=True, null=True)
    access = models.CharField(max_length=254, blank=True, null=True)
    source_nam = models.CharField(max_length=254, blank=True, null=True)
    destinat_4 = models.CharField(max_length=254, blank=True, null=True)
    junction_r = models.CharField(max_length=254, blank=True, null=True)
    destinat_5 = models.CharField(max_length=254, blank=True, null=True)
    destinat_6 = models.CharField(max_length=254, blank=True, null=True)
    destinat_7 = models.CharField(max_length=254, blank=True, null=True)
    destinat_8 = models.CharField(max_length=254, blank=True, null=True)
    maxheight = models.CharField(max_length=254, blank=True, null=True)
    layer = models.CharField(max_length=254, blank=True, null=True)
    bridge = models.CharField(max_length=254, blank=True, null=True)
    loc_name = models.CharField(max_length=254, blank=True, null=True)
    alt_name = models.CharField(max_length=254, blank=True, null=True)
    lit = models.CharField(max_length=254, blank=True, null=True)
    service = models.CharField(max_length=254, blank=True, null=True)
    junction = models.CharField(max_length=254, blank=True, null=True)
    old_name_4 = models.CharField(max_length=254, blank=True, null=True)
    busway_rig = models.CharField(max_length=254, blank=True, null=True)
    ref = models.CharField(max_length=254, blank=True, null=True)
    old_name = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    lanes = models.CharField(max_length=254, blank=True, null=True)
    foot = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    oneway = models.CharField(max_length=254, blank=True, null=True)
    maxspeed = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiLineStringField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'highway'
        verbose_name = _('Highway')
        verbose_name_plural = _('Highway')


class Industrial(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    industrial = models.CharField(max_length=254, blank=True, null=True)
    wikipedia = models.CharField(max_length=254, blank=True, null=True)
    wikidata = models.CharField(max_length=254, blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    landuse = models.CharField(max_length=254, blank=True, null=True)
    descriptio = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'industrial'
        verbose_name = _('Industrial')
        verbose_name_plural = _('Industrial')


class Landuse(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    landuse = models.CharField(max_length=254, blank=True, null=True)
    military_s = models.CharField(max_length=254, blank=True, null=True)
    opening_da = models.CharField(max_length=254, blank=True, null=True)
    check_date = models.CharField(max_length=254, blank=True, null=True)
    residentia = models.CharField(max_length=254, blank=True, null=True)
    industrial = models.CharField(max_length=254, blank=True, null=True)
    name_fr = models.CharField(max_length=254, blank=True, null=True)
    name_en1 = models.CharField(max_length=254, blank=True, null=True)
    military = models.CharField(max_length=254, blank=True, null=True)
    alt_name_f = models.CharField(max_length=254, blank=True, null=True)
    alt_name_e = models.CharField(max_length=254, blank=True, null=True)
    addr_house = models.CharField(max_length=254, blank=True, null=True)
    tourism = models.CharField(max_length=254, blank=True, null=True)
    name_1 = models.CharField(max_length=254, blank=True, null=True)
    phone = models.CharField(max_length=254, blank=True, null=True)
    descriptio = models.CharField(max_length=254, blank=True, null=True)
    highway = models.CharField(max_length=254, blank=True, null=True)
    constructi = models.CharField(max_length=254, blank=True, null=True)
    golf = models.CharField(max_length=254, blank=True, null=True)
    boundary = models.CharField(max_length=254, blank=True, null=True)
    admin_leve = models.CharField(max_length=254, blank=True, null=True)
    addr_subur = models.CharField(max_length=254, blank=True, null=True)
    addr_sub_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_state = models.CharField(max_length=254, blank=True, null=True)
    addr_sta_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_provi = models.CharField(max_length=254, blank=True, null=True)
    addr_pro_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_place = models.CharField(max_length=254, blank=True, null=True)
    addr_pla_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_neigh = models.CharField(max_length=254, blank=True, null=True)
    addr_count = models.CharField(max_length=254, blank=True, null=True)
    addr_city_field = models.CharField(max_length=254, blank=True, null=True)
    ways_in_ar = models.CharField(max_length=254, blank=True, null=True)
    denominati = models.CharField(max_length=254, blank=True, null=True)
    aquacultur = models.CharField(max_length=254, blank=True, null=True)
    addr_hou_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_stree = models.CharField(max_length=254, blank=True, null=True)
    waterway = models.CharField(max_length=254, blank=True, null=True)
    ref = models.CharField(max_length=254, blank=True, null=True)
    name_ur = models.CharField(max_length=254, blank=True, null=True)
    icao = models.CharField(max_length=254, blank=True, null=True)
    iata = models.CharField(max_length=254, blank=True, null=True)
    aeroway = models.CharField(max_length=254, blank=True, null=True)
    access = models.CharField(max_length=254, blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    addr_cit_1 = models.CharField(max_length=254, blank=True, null=True)
    religion = models.CharField(max_length=254, blank=True, null=True)
    amenity = models.CharField(max_length=254, blank=True, null=True)
    building_l = models.CharField(max_length=254, blank=True, null=True)
    sport = models.CharField(max_length=254, blank=True, null=True)
    golf_pract = models.CharField(max_length=254, blank=True, null=True)
    place = models.CharField(max_length=254, blank=True, null=True)
    alt_name = models.CharField(max_length=254, blank=True, null=True)
    natural = models.CharField(max_length=254, blank=True, null=True)
    office = models.CharField(max_length=254, blank=True, null=True)
    leisure = models.CharField(max_length=254, blank=True, null=True)
    building = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    leaf_cycle = models.CharField(max_length=254, blank=True, null=True)
    leaf_type = models.CharField(max_length=254, blank=True, null=True)
    wood = models.CharField(max_length=254, blank=True, null=True)
    barrier = models.CharField(max_length=254, blank=True, null=True)
    addr_city = models.CharField(max_length=254, blank=True, null=True)
    wikipedia_field = models.CharField(max_length=254, blank=True, null=True)
    wikipedia = models.CharField(max_length=254, blank=True, null=True)
    wikidata = models.CharField(max_length=254, blank=True, null=True)
    name_fa = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    type = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'landuse'
        verbose_name = _('Landuse')
        verbose_name_plural = _('Landuse')


class Names(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    noname = models.CharField(max_length=254, blank=True, null=True)
    lanes = models.CharField(max_length=254, blank=True, null=True)
    diet_pesce = models.CharField(max_length=254, blank=True, null=True)
    diet_lacto = models.CharField(max_length=254, blank=True, null=True)
    diet_glute = models.CharField(max_length=254, blank=True, null=True)
    payment_te = models.CharField(max_length=254, blank=True, null=True)
    payment_ma = models.CharField(max_length=254, blank=True, null=True)
    payment_am = models.CharField(max_length=254, blank=True, null=True)
    service_bi = models.CharField(max_length=254, blank=True, null=True)
    service_1 = models.CharField(max_length=254, blank=True, null=True)
    service_2 = models.CharField(max_length=254, blank=True, null=True)
    service_3 = models.CharField(max_length=254, blank=True, null=True)
    diet_organ = models.CharField(max_length=254, blank=True, null=True)
    diet_meat = models.CharField(max_length=254, blank=True, null=True)
    name_nb = models.CharField(max_length=254, blank=True, null=True)
    toll_psv = models.CharField(max_length=254, blank=True, null=True)
    toll_motor = models.CharField(max_length=254, blank=True, null=True)
    toll_mot_1 = models.CharField(max_length=254, blank=True, null=True)
    toll = models.CharField(max_length=254, blank=True, null=True)
    fee_amount = models.CharField(max_length=254, blank=True, null=True)
    camera_mou = models.CharField(max_length=254, blank=True, null=True)
    diet_koshe = models.CharField(max_length=254, blank=True, null=True)
    diet_halal = models.CharField(max_length=254, blank=True, null=True)
    holding_po = models.CharField(max_length=254, blank=True, null=True)
    contact_vk = models.CharField(max_length=254, blank=True, null=True)
    vending = models.CharField(max_length=254, blank=True, null=True)
    bar = models.CharField(max_length=254, blank=True, null=True)
    start_date = models.CharField(max_length=254, blank=True, null=True)
    manufactur = models.CharField(max_length=254, blank=True, null=True)
    camera_typ = models.CharField(max_length=254, blank=True, null=True)
    name_en2 = models.CharField(max_length=254, blank=True, null=True)
    addr_neigh = models.CharField(max_length=254, blank=True, null=True)
    surveillan = models.CharField(max_length=254, blank=True, null=True)
    surveill_1 = models.CharField(max_length=254, blank=True, null=True)
    surveill_2 = models.CharField(max_length=254, blank=True, null=True)
    lamp_type = models.CharField(max_length=254, blank=True, null=True)
    product = models.CharField(max_length=254, blank=True, null=True)
    residentia = models.CharField(max_length=254, blank=True, null=True)
    reservatio = models.CharField(max_length=254, blank=True, null=True)
    guest_hous = models.CharField(max_length=254, blank=True, null=True)
    alt_name_m = models.CharField(max_length=254, blank=True, null=True)
    mobile_pho = models.CharField(max_length=254, blank=True, null=True)
    official_n = models.CharField(max_length=254, blank=True, null=True)
    official_1 = models.CharField(max_length=254, blank=True, null=True)
    official_2 = models.CharField(max_length=254, blank=True, null=True)
    official_3 = models.CharField(max_length=254, blank=True, null=True)
    official_4 = models.CharField(max_length=254, blank=True, null=True)
    official_5 = models.CharField(max_length=254, blank=True, null=True)
    official_6 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_n = models.CharField(max_length=254, blank=True, null=True)
    alt_name_f = models.CharField(max_length=254, blank=True, null=True)
    alt_name_u = models.CharField(max_length=254, blank=True, null=True)
    url = models.CharField(max_length=254, blank=True, null=True)
    shelter_ty = models.CharField(max_length=254, blank=True, null=True)
    toilets_ac = models.CharField(max_length=254, blank=True, null=True)
    toilets = models.CharField(max_length=254, blank=True, null=True)
    toilets_wh = models.CharField(max_length=254, blank=True, null=True)
    waterway = models.CharField(max_length=254, blank=True, null=True)
    attraction = models.CharField(max_length=254, blank=True, null=True)
    government = models.CharField(max_length=254, blank=True, null=True)
    payment_vi = models.CharField(max_length=254, blank=True, null=True)
    payment_ca = models.CharField(max_length=254, blank=True, null=True)
    internet_a = models.CharField(max_length=254, blank=True, null=True)
    brewery = models.CharField(max_length=254, blank=True, null=True)
    operator_t = models.CharField(max_length=254, blank=True, null=True)
    healthcare = models.CharField(max_length=254, blank=True, null=True)
    monitoring = models.CharField(max_length=254, blank=True, null=True)
    facebook = models.CharField(max_length=254, blank=True, null=True)
    cargo = models.CharField(max_length=254, blank=True, null=True)
    brand_wiki = models.CharField(max_length=254, blank=True, null=True)
    club = models.CharField(max_length=254, blank=True, null=True)
    clothes = models.CharField(max_length=254, blank=True, null=True)
    short_name = models.CharField(max_length=254, blank=True, null=True)
    brand_pnb = models.CharField(max_length=254, blank=True, null=True)
    brand_ks = models.CharField(max_length=254, blank=True, null=True)
    brand_azb = models.CharField(max_length=254, blank=True, null=True)
    beauty = models.CharField(max_length=254, blank=True, null=True)
    diplomatic = models.CharField(max_length=254, blank=True, null=True)
    diplomat_1 = models.CharField(max_length=254, blank=True, null=True)
    diplomat_2 = models.CharField(max_length=254, blank=True, null=True)
    crossing_i = models.CharField(max_length=254, blank=True, null=True)
    name_1 = models.CharField(max_length=254, blank=True, null=True)
    disused_sh = models.CharField(max_length=254, blank=True, null=True)
    crossing_r = models.CharField(max_length=254, blank=True, null=True)
    diet_vegan = models.CharField(max_length=254, blank=True, null=True)
    trade = models.CharField(max_length=254, blank=True, null=True)
    phone_1 = models.CharField(max_length=254, blank=True, null=True)
    phone_mobi = models.CharField(max_length=254, blank=True, null=True)
    addr_ref = models.CharField(max_length=254, blank=True, null=True)
    indoor = models.CharField(max_length=254, blank=True, null=True)
    contact_yo = models.CharField(max_length=254, blank=True, null=True)
    contact_li = models.CharField(max_length=254, blank=True, null=True)
    disused_am = models.CharField(max_length=254, blank=True, null=True)
    addr_unit = models.CharField(max_length=254, blank=True, null=True)
    descriptio = models.CharField(max_length=254, blank=True, null=True)
    artwork_ty = models.CharField(max_length=254, blank=True, null=True)
    services = models.CharField(max_length=254, blank=True, null=True)
    swimming_p = models.CharField(max_length=254, blank=True, null=True)
    addr_full = models.CharField(max_length=254, blank=True, null=True)
    bench = models.CharField(max_length=254, blank=True, null=True)
    denominati = models.CharField(max_length=254, blank=True, null=True)
    image = models.CharField(max_length=254, blank=True, null=True)
    network = models.CharField(max_length=254, blank=True, null=True)
    payment_no = models.CharField(max_length=254, blank=True, null=True)
    payment_el = models.CharField(max_length=254, blank=True, null=True)
    payment_cr = models.CharField(max_length=254, blank=True, null=True)
    payment_co = models.CharField(max_length=254, blank=True, null=True)
    second_han = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    lit = models.CharField(max_length=254, blank=True, null=True)
    organic = models.CharField(max_length=254, blank=True, null=True)
    male = models.CharField(max_length=254, blank=True, null=True)
    place_of_w = models.CharField(max_length=254, blank=True, null=True)
    female = models.CharField(max_length=254, blank=True, null=True)
    railway = models.CharField(max_length=254, blank=True, null=True)
    monorail = models.CharField(max_length=254, blank=True, null=True)
    name_en1 = models.CharField(max_length=254, blank=True, null=True)
    recycling_field = models.CharField(max_length=254, blank=True, null=True)
    recyclin_1 = models.CharField(max_length=254, blank=True, null=True)
    religion = models.CharField(max_length=254, blank=True, null=True)
    building_l = models.CharField(max_length=254, blank=True, null=True)
    motorcycle = models.CharField(max_length=254, blank=True, null=True)
    motorcar = models.CharField(max_length=254, blank=True, null=True)
    addr_place = models.CharField(max_length=254, blank=True, null=True)
    craft = models.CharField(max_length=254, blank=True, null=True)
    informatio = models.CharField(max_length=254, blank=True, null=True)
    boundary = models.CharField(max_length=254, blank=True, null=True)
    addr_subur = models.CharField(max_length=254, blank=True, null=True)
    addr_sub_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_state = models.CharField(max_length=254, blank=True, null=True)
    addr_sta_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_provi = models.CharField(max_length=254, blank=True, null=True)
    addr_pro_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_pla_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_pla_2 = models.CharField(max_length=254, blank=True, null=True)
    addr_city_field = models.CharField(max_length=254, blank=True, null=True)
    layer = models.CharField(max_length=254, blank=True, null=True)
    wheelchair = models.CharField(max_length=254, blank=True, null=True)
    name_kk_ar = models.CharField(max_length=254, blank=True, null=True)
    diet_veget = models.CharField(max_length=254, blank=True, null=True)
    power = models.CharField(max_length=254, blank=True, null=True)
    direction = models.CharField(max_length=254, blank=True, null=True)
    supervised = models.CharField(max_length=254, blank=True, null=True)
    parking = models.CharField(max_length=254, blank=True, null=True)
    addr_postb = models.CharField(max_length=254, blank=True, null=True)
    addr_full_field = models.CharField(max_length=254, blank=True, null=True)
    seamark_ty = models.CharField(max_length=254, blank=True, null=True)
    seamark_ha = models.CharField(max_length=254, blank=True, null=True)
    self_servi = models.CharField(max_length=254, blank=True, null=True)
    alt_name_e = models.CharField(max_length=254, blank=True, null=True)
    alt_name_d = models.CharField(max_length=254, blank=True, null=True)
    hypermarke = models.CharField(max_length=254, blank=True, null=True)
    shelter = models.CharField(max_length=254, blank=True, null=True)
    dispensing = models.CharField(max_length=254, blank=True, null=True)
    ferry = models.CharField(max_length=254, blank=True, null=True)
    horse = models.CharField(max_length=254, blank=True, null=True)
    foot = models.CharField(max_length=254, blank=True, null=True)
    door = models.CharField(max_length=254, blank=True, null=True)
    bicycle = models.CharField(max_length=254, blank=True, null=True)
    delivery = models.CharField(max_length=254, blank=True, null=True)
    long_name_field = models.CharField(max_length=254, blank=True, null=True)
    long_name = models.CharField(max_length=254, blank=True, null=True)
    addr_stree = models.CharField(max_length=254, blank=True, null=True)
    addr_house = models.CharField(max_length=254, blank=True, null=True)
    addr_hou_1 = models.CharField(max_length=254, blank=True, null=True)
    addr_floor = models.CharField(max_length=254, blank=True, null=True)
    traffic_ca = models.CharField(max_length=254, blank=True, null=True)
    tower_type = models.CharField(max_length=254, blank=True, null=True)
    locked = models.CharField(max_length=254, blank=True, null=True)
    type = models.CharField(max_length=254, blank=True, null=True)
    destinatio = models.CharField(max_length=254, blank=True, null=True)
    outdoor_se = models.CharField(max_length=254, blank=True, null=True)
    stars = models.CharField(max_length=254, blank=True, null=True)
    rooms = models.CharField(max_length=254, blank=True, null=True)
    mapillary = models.CharField(max_length=254, blank=True, null=True)
    internet_1 = models.CharField(max_length=254, blank=True, null=True)
    air_condit = models.CharField(max_length=254, blank=True, null=True)
    location = models.CharField(max_length=254, blank=True, null=True)
    public_tra = models.CharField(max_length=254, blank=True, null=True)
    bus = models.CharField(max_length=254, blank=True, null=True)
    payment_1 = models.CharField(max_length=254, blank=True, null=True)
    payment_2 = models.CharField(max_length=254, blank=True, null=True)
    payment_de = models.CharField(max_length=254, blank=True, null=True)
    payment_3 = models.CharField(max_length=254, blank=True, null=True)
    payment_4 = models.CharField(max_length=254, blank=True, null=True)
    opening_ho = models.CharField(max_length=254, blank=True, null=True)
    min_age = models.CharField(max_length=254, blank=True, null=True)
    currency_a = models.CharField(max_length=254, blank=True, null=True)
    fuel_diese = models.CharField(max_length=254, blank=True, null=True)
    designatio = models.CharField(max_length=254, blank=True, null=True)
    aeroway = models.CharField(max_length=254, blank=True, null=True)
    fee = models.CharField(max_length=254, blank=True, null=True)
    wifi = models.CharField(max_length=254, blank=True, null=True)
    capacity = models.CharField(max_length=254, blank=True, null=True)
    entrance = models.CharField(max_length=254, blank=True, null=True)
    addr_postc = models.CharField(max_length=254, blank=True, null=True)
    official_7 = models.CharField(max_length=254, blank=True, null=True)
    official_8 = models.CharField(max_length=254, blank=True, null=True)
    contact_fa = models.CharField(max_length=254, blank=True, null=True)
    fax = models.CharField(max_length=254, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    addr_distr = models.CharField(max_length=254, blank=True, null=True)
    smoking = models.CharField(max_length=254, blank=True, null=True)
    building = models.CharField(max_length=254, blank=True, null=True)
    is_in = models.CharField(max_length=254, blank=True, null=True)
    target = models.CharField(max_length=254, blank=True, null=True)
    language_a = models.CharField(max_length=254, blank=True, null=True)
    addr_hou_2 = models.CharField(max_length=254, blank=True, null=True)
    drive_thro = models.CharField(max_length=254, blank=True, null=True)
    level = models.CharField(max_length=254, blank=True, null=True)
    traffic_si = models.CharField(max_length=254, blank=True, null=True)
    traffic_1 = models.CharField(max_length=254, blank=True, null=True)
    man_made = models.CharField(max_length=254, blank=True, null=True)
    height = models.CharField(max_length=254, blank=True, null=True)
    tourism = models.CharField(max_length=254, blank=True, null=True)
    historic = models.CharField(max_length=254, blank=True, null=True)
    embassy = models.CharField(max_length=254, blank=True, null=True)
    diplomat_3 = models.CharField(max_length=254, blank=True, null=True)
    country = models.CharField(max_length=254, blank=True, null=True)
    phone = models.CharField(max_length=254, blank=True, null=True)
    internet_2 = models.CharField(max_length=254, blank=True, null=True)
    takeaway = models.CharField(max_length=254, blank=True, null=True)
    brand_ur = models.CharField(max_length=254, blank=True, null=True)
    brand_pa = models.CharField(max_length=254, blank=True, null=True)
    brand_fa = models.CharField(max_length=254, blank=True, null=True)
    addr_str_1 = models.CharField(max_length=254, blank=True, null=True)
    contact_we = models.CharField(max_length=254, blank=True, null=True)
    contact_tw = models.CharField(max_length=254, blank=True, null=True)
    contact_ph = models.CharField(max_length=254, blank=True, null=True)
    contact_in = models.CharField(max_length=254, blank=True, null=True)
    contact_1 = models.CharField(max_length=254, blank=True, null=True)
    contact_em = models.CharField(max_length=254, blank=True, null=True)
    addr_cit_1 = models.CharField(max_length=254, blank=True, null=True)
    healthca_1 = models.CharField(max_length=254, blank=True, null=True)
    emergency = models.CharField(max_length=254, blank=True, null=True)
    opening_1 = models.CharField(max_length=254, blank=True, null=True)
    dress_code = models.CharField(max_length=254, blank=True, null=True)
    atm = models.CharField(max_length=254, blank=True, null=True)
    official_9 = models.CharField(max_length=254, blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    brand_wi_1 = models.CharField(max_length=254, blank=True, null=True)
    brand_wi_2 = models.CharField(max_length=254, blank=True, null=True)
    brand_en = models.CharField(max_length=254, blank=True, null=True)
    brand_ar = models.CharField(max_length=254, blank=True, null=True)
    brand = models.CharField(max_length=254, blank=True, null=True)
    landuse = models.CharField(max_length=254, blank=True, null=True)
    addr_str_2 = models.CharField(max_length=254, blank=True, null=True)
    addr_hou_3 = models.CharField(max_length=254, blank=True, null=True)
    addr_count = models.CharField(max_length=254, blank=True, null=True)
    addr_city = models.CharField(max_length=254, blank=True, null=True)
    service = models.CharField(max_length=254, blank=True, null=True)
    operator = models.CharField(max_length=254, blank=True, null=True)
    cuisine = models.CharField(max_length=254, blank=True, null=True)
    ele = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPointField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'names'
        verbose_name = _('Name')
        verbose_name_plural = _('Names')


class Natural(models.Model):
    full_id = models.CharField(max_length=254, blank=True, null=True)
    osm_id = models.CharField(max_length=254, blank=True, null=True)
    osm_type = models.CharField(max_length=254, blank=True, null=True)
    natural = models.CharField(max_length=254, blank=True, null=True)
    intermitte = models.CharField(max_length=254, blank=True, null=True)
    golf_pract = models.CharField(max_length=254, blank=True, null=True)
    layer = models.CharField(max_length=254, blank=True, null=True)
    old_name = models.CharField(max_length=254, blank=True, null=True)
    descriptio = models.CharField(max_length=254, blank=True, null=True)
    name_1 = models.CharField(max_length=254, blank=True, null=True)
    managed = models.CharField(max_length=254, blank=True, null=True)
    lit = models.CharField(max_length=254, blank=True, null=True)
    fee = models.CharField(max_length=254, blank=True, null=True)
    icao = models.CharField(max_length=254, blank=True, null=True)
    iata = models.CharField(max_length=254, blank=True, null=True)
    aeroway = models.CharField(max_length=254, blank=True, null=True)
    addr_city_field = models.CharField(max_length=254, blank=True, null=True)
    addr_city = models.CharField(max_length=254, blank=True, null=True)
    historic = models.CharField(max_length=254, blank=True, null=True)
    barrier = models.CharField(max_length=254, blank=True, null=True)
    access = models.CharField(max_length=254, blank=True, null=True)
    addr_stree = models.CharField(max_length=254, blank=True, null=True)
    addr_house = models.CharField(max_length=254, blank=True, null=True)
    building = models.CharField(max_length=254, blank=True, null=True)
    tourism = models.CharField(max_length=254, blank=True, null=True)
    alt_name_2 = models.CharField(max_length=254, blank=True, null=True)
    loc_name = models.CharField(max_length=254, blank=True, null=True)
    industrial = models.CharField(max_length=254, blank=True, null=True)
    leisure = models.CharField(max_length=254, blank=True, null=True)
    man_made = models.CharField(max_length=254, blank=True, null=True)
    long_name_field = models.CharField(max_length=254, blank=True, null=True)
    short_name = models.CharField(max_length=254, blank=True, null=True)
    ref = models.CharField(max_length=254, blank=True, null=True)
    alt_name_c = models.CharField(max_length=254, blank=True, null=True)
    website = models.CharField(max_length=254, blank=True, null=True)
    source_nam = models.CharField(max_length=254, blank=True, null=True)
    gns_id = models.CharField(max_length=254, blank=True, null=True)
    landuse = models.CharField(max_length=254, blank=True, null=True)
    surface = models.CharField(max_length=254, blank=True, null=True)
    wikipedia_field = models.CharField(max_length=254, blank=True, null=True)
    alt_name_a = models.CharField(max_length=254, blank=True, null=True)
    name_ar1 = models.CharField(max_length=254, blank=True, null=True)
    int_name = models.CharField(max_length=254, blank=True, null=True)
    place = models.CharField(max_length=254, blank=True, null=True)
    name_en1 = models.CharField(max_length=254, blank=True, null=True)
    wikipedia = models.CharField(max_length=254, blank=True, null=True)
    wikidata = models.CharField(max_length=254, blank=True, null=True)
    sqkm = models.CharField(max_length=254, blank=True, null=True)
    name_zh_ha = models.CharField(max_length=254, blank=True, null=True)
    name_zh_1 = models.CharField(max_length=254, blank=True, null=True)
    name_zh = models.CharField(max_length=254, blank=True, null=True)
    name_vi = models.CharField(max_length=254, blank=True, null=True)
    name_ur = models.CharField(max_length=254, blank=True, null=True)
    name_uk = models.CharField(max_length=254, blank=True, null=True)
    name_tr = models.CharField(max_length=254, blank=True, null=True)
    name_th = models.CharField(max_length=254, blank=True, null=True)
    name_sw = models.CharField(max_length=254, blank=True, null=True)
    name_sl = models.CharField(max_length=254, blank=True, null=True)
    name_sk = models.CharField(max_length=254, blank=True, null=True)
    name_ru = models.CharField(max_length=254, blank=True, null=True)
    name_pt = models.CharField(max_length=254, blank=True, null=True)
    name_ps = models.CharField(max_length=254, blank=True, null=True)
    name_pnb = models.CharField(max_length=254, blank=True, null=True)
    name_pl = models.CharField(max_length=254, blank=True, null=True)
    name_no = models.CharField(max_length=254, blank=True, null=True)
    name_nl = models.CharField(max_length=254, blank=True, null=True)
    name_mzn = models.CharField(max_length=254, blank=True, null=True)
    name_ms = models.CharField(max_length=254, blank=True, null=True)
    name_lt = models.CharField(max_length=254, blank=True, null=True)
    name_la = models.CharField(max_length=254, blank=True, null=True)
    name_ku = models.CharField(max_length=254, blank=True, null=True)
    name_ko = models.CharField(max_length=254, blank=True, null=True)
    name_kk = models.CharField(max_length=254, blank=True, null=True)
    name_ka = models.CharField(max_length=254, blank=True, null=True)
    name_ja = models.CharField(max_length=254, blank=True, null=True)
    name_it = models.CharField(max_length=254, blank=True, null=True)
    name_is = models.CharField(max_length=254, blank=True, null=True)
    name_io = models.CharField(max_length=254, blank=True, null=True)
    name_ia = models.CharField(max_length=254, blank=True, null=True)
    name_hy = models.CharField(max_length=254, blank=True, null=True)
    name_hu = models.CharField(max_length=254, blank=True, null=True)
    name_hr = models.CharField(max_length=254, blank=True, null=True)
    name_hi = models.CharField(max_length=254, blank=True, null=True)
    name_he = models.CharField(max_length=254, blank=True, null=True)
    name_glk = models.CharField(max_length=254, blank=True, null=True)
    name_fr = models.CharField(max_length=254, blank=True, null=True)
    name_fi = models.CharField(max_length=254, blank=True, null=True)
    name_fa = models.CharField(max_length=254, blank=True, null=True)
    name_et = models.CharField(max_length=254, blank=True, null=True)
    name_es = models.CharField(max_length=254, blank=True, null=True)
    name_eo = models.CharField(max_length=254, blank=True, null=True)
    name_el = models.CharField(max_length=254, blank=True, null=True)
    name_de = models.CharField(max_length=254, blank=True, null=True)
    name_cs = models.CharField(max_length=254, blank=True, null=True)
    name_ckb = models.CharField(max_length=254, blank=True, null=True)
    name_ca = models.CharField(max_length=254, blank=True, null=True)
    name_bs = models.CharField(max_length=254, blank=True, null=True)
    name_bn = models.CharField(max_length=254, blank=True, null=True)
    name_azb = models.CharField(max_length=254, blank=True, null=True)
    name_az = models.CharField(max_length=254, blank=True, null=True)
    name_arz = models.CharField(max_length=254, blank=True, null=True)
    name_arc = models.CharField(max_length=254, blank=True, null=True)
    name_ang = models.CharField(max_length=254, blank=True, null=True)
    gns_uni = models.CharField(max_length=254, blank=True, null=True)
    gns_dsg = models.CharField(max_length=254, blank=True, null=True)
    alt_name_z = models.CharField(max_length=254, blank=True, null=True)
    alt_name_y = models.CharField(max_length=254, blank=True, null=True)
    alt_name_v = models.CharField(max_length=254, blank=True, null=True)
    alt_name_u = models.CharField(max_length=254, blank=True, null=True)
    alt_name_t = models.CharField(max_length=254, blank=True, null=True)
    alt_name_1 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_s = models.CharField(max_length=254, blank=True, null=True)
    alt_name_r = models.CharField(max_length=254, blank=True, null=True)
    alt_name_p = models.CharField(max_length=254, blank=True, null=True)
    alt_name_3 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_n = models.CharField(max_length=254, blank=True, null=True)
    alt_name_l = models.CharField(max_length=254, blank=True, null=True)
    alt_name_k = models.CharField(max_length=254, blank=True, null=True)
    alt_name_4 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_j = models.CharField(max_length=254, blank=True, null=True)
    alt_name_i = models.CharField(max_length=254, blank=True, null=True)
    alt_name_h = models.CharField(max_length=254, blank=True, null=True)
    alt_name_5 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_6 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_7 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_f = models.CharField(max_length=254, blank=True, null=True)
    alt_name_8 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_e = models.CharField(max_length=254, blank=True, null=True)
    alt_name_9 = models.CharField(max_length=254, blank=True, null=True)
    alt_name10 = models.CharField(max_length=254, blank=True, null=True)
    alt_name11 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_d = models.CharField(max_length=254, blank=True, null=True)
    alt_name12 = models.CharField(max_length=254, blank=True, null=True)
    alt_name13 = models.CharField(max_length=254, blank=True, null=True)
    alt_name_b = models.CharField(max_length=254, blank=True, null=True)
    alt_name14 = models.CharField(max_length=254, blank=True, null=True)
    alt_name15 = models.CharField(max_length=254, blank=True, null=True)
    alt_name = models.CharField(max_length=254, blank=True, null=True)
    water = models.CharField(max_length=254, blank=True, null=True)
    golf = models.CharField(max_length=254, blank=True, null=True)
    name_en = models.CharField(max_length=254, blank=True, null=True)
    name_ar = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254, blank=True, null=True)
    wetland = models.CharField(max_length=254, blank=True, null=True)
    type = models.CharField(max_length=254, blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'natural'
        verbose_name = _('Natural')
        verbose_name_plural = _('Natural')



